# Generated by Django 3.1.7 on 2021-03-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_remove_competitor_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='champion_winning_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='leaderboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='leaderboard.leaderboard'),
        ),
        migrations.AlterField(
            model_name='competitordeck',
            name='competitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='leaderboard.competitor'),
        ),
    ]
