# Generated by Django 3.1.7 on 2021-03-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0005_auto_20210328_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='defended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_defenses', to='leaderboard.competitor'),
        ),
        migrations.AlterField(
            model_name='result',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_wins', to='leaderboard.competitor'),
        ),
    ]
