# Generated by Django 3.1.7 on 2021-03-29 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_auto_20210328_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaderboard.challenge'),
        ),
    ]
