# Generated by Django 3.2 on 2021-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_color',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
